const types = {
    DELETE_TODO: 'DELETE_TODO',
    GET_PATIENTS: 'GET_PATIENTS',
    GET_PATIENTS_SUCCEEDED: 'GET_PATIENTS_SUCCEEDED',
    GET_PATIENTS_FAILED: 'GET_PATIENTS_FAILED',
    SUBMIT_TODO: 'SUBMIT_TODO',
    SWITCH_TAB: 'SWITCH_TAB',
    UNDELETE_TODO: 'UNDELETE_TODO',
};

export default types;
